-- dev_db.member_output definition

CREATE TABLE `member_output` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `user_id` bigint NOT NULL COMMENT '用户ID',
  `user_name` varchar(50) DEFAULT NULL COMMENT '用户名（开放 API 使用）',
  `stat_date` date NOT NULL COMMENT '统计日期',
  `prd_count` int DEFAULT '0' COMMENT 'PRD文档数',
  `api_count` int DEFAULT '0' COMMENT 'API接口数',
  `java_lines` int DEFAULT '0' COMMENT 'Java代码行数',
  `frontend_lines` int DEFAULT '0' COMMENT '前端代码行数',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `project_root_name` varchar(255) DEFAULT NULL COMMENT '项目根目录名（用于标识产出所属项目）',
  `prd_doc_count` int DEFAULT '0' COMMENT 'PRD 文档数量',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `data_model_doc_count` int DEFAULT '0' COMMENT '数据模型文档数量',
  `api_doc_count` int DEFAULT '0' COMMENT 'API 接口文档数量',
  `java_file_count` int DEFAULT '0' COMMENT 'Java 文件数量',
  `java_code_lines` int DEFAULT '0' COMMENT 'Java 代码行数',
  `core_biz_service_count` int DEFAULT '0' COMMENT '核心业务服务数量',
  `entity_count` int DEFAULT '0' COMMENT '数据库实体数量',
  `frontend_component_count` int DEFAULT '0' COMMENT '前端组件数量',
  `frontend_page_count` int DEFAULT '0' COMMENT '前端页面数量',
  `frontend_common_component_count` int DEFAULT '0' COMMENT '前端公共组件数量',
  `ts_code_lines` int DEFAULT '0' COMMENT 'TypeScript 代码行数',
  `frontend_code_lines` int DEFAULT '0' COMMENT '前端代码行数',
  `sql_script_count` int DEFAULT '0' COMMENT 'SQL 脚本数量',
  `test_file_count` int DEFAULT '0' COMMENT '测试文件数量',
  `total_code_lines` int DEFAULT '0' COMMENT '总代码行数',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_user_date_project` (`user_name`,`stat_date`,`project_root_name`),
  KEY `idx_stat_date` (`stat_date`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_user_name_date` (`user_name`,`stat_date`),
  KEY `idx_project_date` (`project_root_name`,`stat_date`),
  KEY `idx_user_project_date` (`user_id`,`project_root_name`,`stat_date`),
  KEY `idx_stat_date_user` (`stat_date`,`user_id`)
) ENGINE=InnoDB AUTO_INCREMENT=100 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='成员产出表';