ALTER TABLE `member_output`
    CHANGE COLUMN `output_date` `stat_date` DATE NOT NULL COMMENT '统计日期',
    MODIFY COLUMN `output_type` VARCHAR(50) DEFAULT NULL COMMENT '历史产出类型',
    MODIFY COLUMN `resource_id` BIGINT DEFAULT NULL COMMENT '历史资源ID',
    ADD COLUMN `prd_count` INT DEFAULT 0 COMMENT 'PRD 数量' AFTER `stat_date`,
    ADD COLUMN `java_lines` INT DEFAULT 0 COMMENT 'Java 代码行数' AFTER `prd_count`,
    ADD COLUMN `frontend_lines` INT DEFAULT 0 COMMENT '前端代码行数' AFTER `java_lines`,
    ADD COLUMN `prd_doc_count` INT DEFAULT 0 COMMENT 'PRD 文档数量' AFTER `frontend_lines`,
    ADD COLUMN `data_model_doc_count` INT DEFAULT 0 COMMENT '数据模型文档数量' AFTER `prd_doc_count`,
    ADD COLUMN `api_doc_count` INT DEFAULT 0 COMMENT 'API 文档数量' AFTER `data_model_doc_count`,
    ADD COLUMN `java_file_count` INT DEFAULT 0 COMMENT 'Java 文件数量' AFTER `api_doc_count`,
    ADD COLUMN `java_code_lines` INT DEFAULT 0 COMMENT 'Java 代码行数' AFTER `java_file_count`,
    ADD COLUMN `api_count` INT DEFAULT 0 COMMENT 'API 数量' AFTER `java_code_lines`,
    ADD COLUMN `core_biz_service_count` INT DEFAULT 0 COMMENT '核心业务 Service 数量' AFTER `api_count`,
    ADD COLUMN `entity_count` INT DEFAULT 0 COMMENT '实体数量' AFTER `core_biz_service_count`,
    ADD COLUMN `frontend_component_count` INT DEFAULT 0 COMMENT '前端组件数量' AFTER `entity_count`,
    ADD COLUMN `frontend_page_count` INT DEFAULT 0 COMMENT '前端页面数量' AFTER `frontend_component_count`,
    ADD COLUMN `frontend_common_component_count` INT DEFAULT 0 COMMENT '前端公共组件数量' AFTER `frontend_page_count`,
    ADD COLUMN `ts_code_lines` INT DEFAULT 0 COMMENT 'TS 代码行数' AFTER `frontend_common_component_count`,
    ADD COLUMN `frontend_code_lines` INT DEFAULT 0 COMMENT '前端代码行数' AFTER `ts_code_lines`,
    ADD COLUMN `sql_script_count` INT DEFAULT 0 COMMENT 'SQL 脚本数量' AFTER `frontend_code_lines`,
    ADD COLUMN `test_file_count` INT DEFAULT 0 COMMENT '测试文件数量' AFTER `sql_script_count`,
    ADD COLUMN `total_code_lines` INT DEFAULT 0 COMMENT '总代码行数' AFTER `test_file_count`,
    ADD COLUMN `remark` VARCHAR(1000) DEFAULT NULL COMMENT '备注' AFTER `total_code_lines`,
    ADD COLUMN `project_root_name` VARCHAR(255) DEFAULT NULL COMMENT '项目根目录名称' AFTER `remark`,
    ADD COLUMN `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间' AFTER `created_at`,
    ADD INDEX `idx_stat_date` (`stat_date`),
    ADD INDEX `idx_project_root_name` (`project_root_name`);
