CREATE TABLE IF NOT EXISTS gitlab_runtime_config (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    base_url VARCHAR(500) DEFAULT NULL,
    private_token VARCHAR(1000) DEFAULT NULL,
    webhook_token VARCHAR(1000) DEFAULT NULL,
    schedules_enabled TINYINT NOT NULL DEFAULT 0,
    daily_analyze_cron VARCHAR(128) DEFAULT NULL,
    daily_report_cron VARCHAR(128) DEFAULT NULL,
    backfill_cron VARCHAR(128) DEFAULT NULL,
    enabled TINYINT NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ai_model_config (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    provider_name VARCHAR(128) DEFAULT NULL,
    base_url VARCHAR(500) DEFAULT NULL,
    model_name VARCHAR(255) DEFAULT NULL,
    api_key VARCHAR(1000) DEFAULT NULL,
    prompt_version VARCHAR(128) DEFAULT NULL,
    request_timeout_ms INT NOT NULL DEFAULT 30000,
    max_retries INT NOT NULL DEFAULT 2,
    enabled TINYINT NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
